apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: eks-demo
type: Opaque
stringData:
  DB_HOST: eks-postgres-cluster-db.c5e2g246adrq.eu-west-1.rds.amazonaws.com
  DB_NAME: appdb
  DB_USER: appuser
  DB_PASSWORD: SecurePass123!